version: '3.4'

services:
  message.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"